const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { createRequire } = require('node:module');
const { pathToFileURL } = require('node:url');
// shortcut: reuse the sibling engine's browser and public fixtures; replace paths for standalone CI.
const { chromium } = createRequire(path.resolve('../SafeAngle-engine/package.json'))('playwright');
const { createClient } = createRequire(path.resolve('frontend/package.json'))('@supabase/supabase-js');

async function main() {
  const source = await fs.readFile('frontend/src/lib/supabaseClient.ts', 'utf8');
  const url = source.match(/https:\/\/[a-z]+\.supabase\.co/)?.[0];
  const key = source.match(/sb_publishable_[A-Za-z0-9_-]+/)?.[0];
  assert(url && key, 'Public client configuration required; never use service keys here');
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  let db, manager;
  const outsider = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const summary = { checks: [], errors, cleanup: false };
  const fixture = path.resolve('../SafeAngle-engine/.local/fixtures/short.webm');
  try {
    await page.goto(process.env.VERIFY_STORAGE_URL ?? 'http://127.0.0.1:3198/', { waitUntil: 'networkidle' });
    await page.locator('#dashboard-name').fill(`저장 연결 확인 ${Date.now()}`);
    await page.getByRole('button', { name: '시작하기' }).click();
    await page.locator('.dashboard-modal').waitFor({ state: 'hidden', timeout: 30000 });
    const session = await page.evaluate(() => {
      const name = Object.keys(localStorage).find((key) => key.startsWith('sb-') && key.endsWith('-auth-token'));
      return name ? JSON.parse(localStorage.getItem(name)) : null;
    });
    assert(session?.access_token && session?.refresh_token, 'Owned verification session missing');
    db = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const connected = await db.auth.setSession({ access_token: session.access_token, refresh_token: session.refresh_token });
    assert(!connected.error); manager = connected.data.user.id;
    await page.locator('.sidebar-add').click();
    await page.locator('#dashboard-name').fill('공개 영상 연결 확인');
    await page.getByRole('button', { name: '평가 시작' }).click();
    await page.waitForURL('**/upload/1/');
    await page.locator('.upload-file-input').setInputFiles(fixture);
    await page.getByText(/영상이 저장(됐|되었)습니다/).waitFor({ timeout: 60000 });
    let item = await page.evaluate(() => JSON.parse(localStorage.getItem('safeangle.dashboard.v1')).evaluations[0]);
    const video = await db.from('assessment_videos').select('storage_path,duration_seconds').eq('assessment_id', item.assessmentId).single();
    assert(!video.error && video.data.storage_path.startsWith(`${manager}/${item.assessmentId}/`));
    const storagePath = video.data.storage_path;
    summary.checks.push('actual private resumable upload, video record');
    const original = await fs.readFile(fixture);
    const download = await db.storage.from('assessment-videos').download(storagePath);
    assert(!download.error);
    assert.deepEqual(Buffer.from(await download.data.arrayBuffer()), original);
    summary.checks.push('owner download matches original bytes');
    await page.getByRole('button', { name: /다음: 앉아서/ }).click();
    await page.waitForURL('**/upload/2/');
    await page.getByRole('button', { name: /건너뛰기/ }).click();
    await page.waitForURL('**/upload/3/');
    await page.getByRole('button', { name: /건너뛰기/ }).click();
    await page.waitForURL('**/review/');
    await page.getByRole('button', { name: /다음: 작업 조건 입력/ }).click();
    await page.waitForURL('**/questions/1/2/');
    await page.locator('input[name="1-force"][value="under5"]').check();
    await page.locator('input[name="1-impact"][value="no"]').check();
    await page.getByRole('button', { name: /다음 질문으로/ }).click();
    await page.waitForURL('**/questions/1/3/');
    await page.locator('input[name="1-coupling"][value="good"]').check();
    await page.getByRole('button', { name: /다음 질문으로/ }).click();
    await page.waitForURL('**/questions/1/4/');
    await page.locator('input[name="1-static"][value="no"]').check();
    const inputSaved = page.waitForResponse((response) => response.url().includes('/rest/v1/assessment_posture_inputs') && response.request().method() === 'POST' && response.ok() && response.request().postDataJSON()?.some((row) => row.answers?.repeated === 'unknown'));
    await page.locator('input[name="1-repeated"][value="unknown"]').check();
    await inputSaved;
    await page.reload({ waitUntil: 'networkidle' });
    await page.locator('input[name="1-repeated"][value="unknown"]').waitFor();
    assert(await page.locator('input[name="1-repeated"][value="unknown"]').isChecked());
    await page.waitForFunction(() => document.querySelector('.scene-preview video')?.readyState >= 1);
    await page.locator('.scene-preview video').evaluate(async (video) => { video.muted = true; await video.play(); });
    await page.waitForFunction(() => document.querySelector('.scene-preview video').currentTime > 0.1);
    await page.locator('.scene-preview video').evaluate((video) => video.pause());
    summary.checks.push('answers, skips, unknown, video restored after reload');
    const inputs = await db.from('assessment_posture_inputs').select('*').eq('assessment_id', item.assessmentId);
    assert(!inputs.error && inputs.data.length === 3);
    assert(inputs.data.find((x) => x.posture_type === 'push_pull').is_skipped);
    assert.equal(inputs.data.find((x) => x.posture_type === 'lift_transfer').answers.repeated, 'unknown');
    const storage = await import(pathToFileURL(path.resolve('frontend/src/lib/analysisStorage.ts')).href);
    item = await page.evaluate(() => JSON.parse(localStorage.getItem('safeangle.dashboard.v1')).evaluations[0]);
    item.selectedTimes[1] = 2;
    await storage.saveAssessmentInputs(db, manager, item);
    const selected = await db.from('assessment_posture_inputs').select('selected_time_seconds,answers').eq('assessment_id', item.assessmentId).eq('posture_type', 'lift_transfer').single();
    assert.equal(Number(selected.data.selected_time_seconds), 2);
    assert.equal(selected.data.answers.repeated, 'unknown');
    const parts = Object.fromEntries(['trunk','neck','legs','upperArm','lowerArm','wrist'].map((key) => [key, { score: 1, source: 'human' }]));
    const fixtureResult = { status: 'pending', final: null, scene: { videoId: 'storage-verification-fixture', frameIndex: 10, timeSec: 2, side: 'left' }, parts, verificationOnly: true };
    await storage.persistAnalysisResult(db, manager, item, 1, fixtureResult, storagePath);
    let assessment = await db.from('assessments').select('result,reba_score,status').eq('id', item.assessmentId).single();
    assert(!assessment.error); assert.equal(assessment.data.reba_score, null); assert.equal(assessment.data.status, 'needs_review');
    assert.equal((await storage.restoreAnalysisResults(db, manager, item))[1].scene.timeSec, 2);
    await assert.rejects(storage.persistAnalysisResult(db, manager, item, 1, { ...fixtureResult, final: 0 }, storagePath));
    await assert.rejects(storage.persistAnalysisResult(db, manager, item, 1, { ...fixtureResult, scene: { ...fixtureResult.scene, timeSec: 3 } }, storagePath));
    await assert.rejects(storage.persistAnalysisResult(db, manager, item, 1, { ...fixtureResult, parts: { ...parts, trunk: { score: 1, source: 'vlm' } } }, storagePath));
    await assert.rejects(storage.persistAnalysisResult(db, manager, item, 1, fixtureResult, 'wrong-path'));
    item.answers[1].repeated = 'no';
    await storage.saveAssessmentInputs(db, manager, item);
    await storage.persistAnalysisResult(db, manager, item, 1, { ...fixtureResult, status: 'complete', final: 1 }, storagePath);
    assessment = await db.from('assessments').select('reba_score,status').eq('id', item.assessmentId).single();
    assert(!assessment.error); assert.equal(assessment.data.reba_score, 1); assert.equal(assessment.data.status, 'completed');
    await storage.saveAssessmentInputs(db, manager, item);
    assessment = await db.from('assessments').select('reba_score').eq('id', item.assessmentId).single();
    assert.equal(assessment.data.reba_score, 1, 'unchanged JSONB answers must preserve score');
    item.answers[1].repeated = 'yes';
    await storage.saveAssessmentInputs(db, manager, item);
    assessment = await db.from('assessments').select('result,reba_score').eq('id', item.assessmentId).single();
    assert.equal(assessment.data.result, null); assert.equal(assessment.data.reba_score, null);
    const files = await import(pathToFileURL(path.resolve('frontend/src/lib/videoStorage.ts')).href);
    assert(files.validateVideoFile(new File([], 'empty.webm', { type: 'video/webm' })));
    assert(files.validateVideoFile({ name: 'big.webm', type: 'video/webm', size: files.MAX_VIDEO_BYTES + 1 }));
    summary.checks.push('selected time restored, pending stays null, result fixtures round trip, stale result rejected, input edits invalidate score, empty/oversize rejected');
    await page.evaluate(() => document.fonts.ready);
    const font = await page.evaluate(() => ({ body: getComputedStyle(document.body).fontFamily, input: getComputedStyle(document.querySelector('input')).fontFamily, loaded: [...document.fonts].some((x) => /pretendard/i.test(x.family) && x.status === 'loaded') }));
    assert.match(font.body, /pretendard/i); assert.equal(font.body, font.input); assert(font.loaded);
    summary.font = font;
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => document.querySelector('.dashboard-main-wrap').getBoundingClientRect().left < 1 && document.querySelector('.dashboard-sidebar').getBoundingClientRect().right < 1);
    await fs.mkdir('.local/storage-verification', { recursive: true });
    await page.screenshot({ path: '.local/storage-verification/mobile.png', fullPage: true, animations: 'disabled' });
    summary.mobile = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, overflow: [...document.querySelectorAll('body *')].filter((x) => x.getBoundingClientRect().right > innerWidth + 1).map((x) => x.className).slice(0, 12) }));
    assert.equal(summary.mobile.scrollWidth, summary.mobile.width);
    summary.checks.push('self-hosted Pretendard loaded, inherited controls, 390px screenshot');
    const outsiderLogin = await outsider.auth.signInAnonymously();
    assert(!outsiderLogin.error);
    const denied = await outsider.storage.from('assessment-videos').download(storagePath);
    assert(denied.error && !denied.data);
    const hidden = await outsider.from('assessments').select('id').eq('id', item.assessmentId);
    assert(!hidden.error && hidden.data.length === 0);
    const publicGet = await fetch(`${url}/storage/v1/object/public/assessment-videos/${storagePath}`);
    assert(!publicGet.ok);
    summary.checks.push('other authenticated manager and public URL cannot read video/assessment');
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
    if (db && manager) {
      const rows = await db.from('assessment_videos').select('storage_path').eq('manager_id', manager);
      const paths = (rows.data ?? []).map((x) => x.storage_path);
      assert(paths.every((x) => x.startsWith(`${manager}/`)));
      if (paths.length) { const removed = await db.storage.from('assessment-videos').remove(paths); assert(!removed.error); }
      for (const table of ['assessment_videos', 'assessment_posture_inputs', 'assessments', 'people']) {
        const removed = await db.from(table).delete().eq('manager_id', manager); assert(!removed.error, table);
      }
      const removed = await db.from('managers').delete().eq('id', manager); assert(!removed.error);
      summary.cleanup = true;
    }
    await fs.mkdir('.local/storage-verification', { recursive: true });
    await fs.writeFile('.local/storage-verification/results.json', JSON.stringify(summary, null, 2));
    console.log(JSON.stringify(summary, null, 2));
  }
}
main().catch((error) => { console.error(error.name, error.message); process.exitCode = 1; });
